// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// FetchItems provides a mock function with given fields:
func (_m *MockClient) FetchItems() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateEnv provides a mock function with given fields:
func (_m *MockClient) GenerateEnv() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateEnv")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetFoldersIDs provides a mock function with given fields: foldersNames
func (_m *MockClient) SetFoldersIDs(foldersNames []string) error {
	ret := _m.Called(foldersNames)

	if len(ret) == 0 {
		panic("no return value specified for SetFoldersIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(foldersNames)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
